### ISSUE TITLE
Sound: "New Level" at End of Level

### ISSUE THREAD

**Issue by James-Gryphon** [grassblade-entertainment/greebles-issues#18]
Presently, the "New Level" sound plays when a level is won. It should play simultaneously with the screen swap and beginning of path generation.

**Comment by habnabit** [comment]
does not appear to be fixed in mac 0.3.1 (whose application bundle says 1.0, but `itch.io` claimed to be the 0.3.1 download). _sometimes_ the sound plays at the start of the next level, and _sometimes_ it's played upon death of the last greeble. i can't discern when this happens. i can try to record a video.
